---
- name: Test targets are network nodes
  assert:
    that:
      - ansible_network_os | d()

- name: Test commands are set when mode is not dryrun
  assert:
    that:
      - rntebr_command | d()
      - rntebr_command is string
    fail_msg: |
      rntebr_command: {{ rntebr_command | d('undef') }}
  when:
    - rntebr_mode != 'dryrun'

- name: Test variables are OK
  assert:
    that:
      - rntebr_mode | d()
      - rntebr_mode is string
      - rntebr_dump_path_prefix | d()
      - rntebr_dump_path_prefix is string
      - rntebr_targets_should_be_found | d()
      - rntebr_targets_should_be_found is in [true, false]
      - rntebr_ignore_errors is defined
      - rntebr_ignore_errors is in [true, false]
      - rntebr_targets_patterns | d()
      - rntebr_targets_patterns is sequence
      - rntebr_targets_patterns | length > 0
    fail_msg: |
      rntebr_mode: {{ rntebr_mode | d('undef') }}
      rntebr_dump_path_prefix: {{ rntebr_dump_path_prefix | d('undef') }}
      rntebr_targets_should_be_found:
        {{ rntebr_targets_should_be_found | d('undef') }}
      rntebr_ignore_errors: {{ rntebr_ignore_errors | d('undef') }}
      rntebr_targets_patterns: {{ rntebr_targets_patterns | d('undef') }}

# vim:sw=2:ts=2:et:
